Bug 1335228 - Change owner of Spark log to spark instead of hadoop user.
mozilla/emr-bootstrap-spark pull request #61
Opened 2017-02-10 09:11 UTC by jezdez

2017-02-10 11:35 UTC, vitillo approved these changes
LGTM. Has this been manually tested?

2017-02-10 13:01 UTC, jezdez commented
@vitillo Can you elaborate what manually testing means in that case?

2017-02-10 13:16 UTC, vitillo commented
As this project doesn't have any automated test suite, I would like to know how you verified (supposedly "manually") that the [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1335228#c0) mentioned by Sam has been fixed.

2017-02-10 13:18 UTC, jezdez commented
@vitillo Right, I haven't run the script, do you mean by running the ansible playbook?

2017-02-10 13:26 UTC, vitillo commented
Unfortunately we don't have [different environments yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1312747) so you can't just run the ansible playbook to test a change in the bootstrap script. 

One way to do it would be to create a vanilla EMR cluster (i.e. not from within ATMO), run the bootstrap script manually and finally launch a Spark job and verify that error Sam mentioned is gone.

An even better way would be to fix [Bug 1312747](https://bugzilla.mozilla.org/show_bug.cgi?id=1312747) before so that testing these kind of changes will become much easier.

2017-02-10 13:37 UTC, jezdez commented
@vitillo Okay, that's some viable yak you just offered to be shaved. I accept :)

2017-02-10 13:37 UTC, vitillo commented
\o/

2018-01-17 22:26 UTC, acmiyaguchi commented
@jezdez Bumping this PR since all the requisites are in order. Changing the owner of the spark log does not fix the original bug. One of the reasons for this might be because spark is writing its event log to hdfs. It would still be nice to obtain a copy of the spark application logs outside of the yarn application logs.

2018-01-17 22:26 UTC, acmiyaguchi requested changes
This doesn't fix the problem described in the bug.

2020-02-14 18:29 UTC, closed without merging